---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
jobs:
  include:
    - name: Lint validation
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="helm tox" bash
      script:
        - tox -e lint
        - bash -c 'shopt -s globstar; shellcheck **/*.sh'
        - find k8s -name Chart.yaml -exec dirname {} \; | xargs helm lint
    - name: Docker validation on Ubuntu 18.04 LTS Bare Metal
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="docker make" bash
      script:
        - HOST_IP=$(ip route get 8.8.8.8 | grep "^8." | awk '{ print $7 }') ./install.sh
        - ./deploy.sh
    - name: Kubernetes + Multus CNI on Ubuntu 18.04 LTS Bare Metal
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="docker make" bash
      script:
        - ./install.sh
        - ./deploy.sh
      env:
        - DEPLOYMENT_TYPE=k8s
    - name: Kubernetes + DANM CNI on Ubuntu 18.04 LTS Bare Metal
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="docker make" bash
      script:
        - ./install.sh
        - ./deploy.sh
      env:
        - DEPLOYMENT_TYPE=k8s
        - MULTI_CNI=danm
