---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-config
data:
  enb: |
    mcc: "001"
    mnc: "01"
    rat_type: 6 # E-UTRAN
    tai: 0x0001
    eci: 0x00000001
    local_addresses:
      s1c_ip: "172.21.1.11"
      s1u_ip: "172.21.0.11"
    mme_addr: "172.21.1.12:36412"
    prom_addr:
    subscribers:
      - imsi: "001010000000001"
        msisdn: "814000000001"
        imeisv: "1234500000001"
        src_ip: "10.0.3.201"
        i_tei: 0
        type: "external"
        euu_if_name: "eth1"
        http_url: ""
        reattach_on_reload: false
  mme: |
    mcc: "001"
    mnc: "01"
    apn: "gw-tester.go-gtp.example"
    local_addresses:
      s1c_addr: "172.21.1.12:36412"
      s11_ip: "172.22.0.12"
    sgw_s11_ip: "172.22.0.13"
    pgw_s5c_ip: "172.25.1.14"
  pgw: |
    local_addresses:
      s5c_ip: "172.25.1.14"
      s5u_ip: "172.25.0.14"
    sgi_if_name: "eth2"
    route_subnet: "10.0.1.0/24"
  sgw: |
    local_addresses:
      s11_ip: "172.22.0.13"
      s1u_ip: "172.21.0.13"
      s5c_ip: "172.25.1.13"
      s5u_ip: "172.25.0.13"
