---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: enb
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-euu", "interface": "net1" },
      { "name": "lte-s1c", "interface": "net2" },
      { "name": "lte-s1u", "interface": "net3" }
    ]'
spec:
  restartPolicy: OnFailure
  containers:
  - image: electrocucaracha/enb
    name: enb
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command:
      - "sh"
    args:
      - "/opt/gw-tester/script/init.sh"
    volumeMounts:
      - name: init-script
        mountPath: /opt/gw-tester/script
  volumes:
    - name: init-script
      configMap:
        name: enb-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enb-init-script
data:
  init.sh: |
    s1c_ip=$(ifconfig net2 | awk '/inet addr/{print substr($2,6)}')
    s1u_ip=$(ifconfig net3 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s1c_ip:.*|s1c_ip: \"${s1c_ip}\"|g" /etc/gw-tester/enb.yml
    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/enb.yml
    sed -i "s|euu_if_name:.*|euu_if_name: \"net1\"|g" /etc/gw-tester/enb.yml
    sed -i "s|mme_addr:.*|mme_addr: \"${MME_S11_ADDR}\"|g" /etc/gw-tester/enb.yml

    /opt/gw-tester/bin/enb -config /etc/gw-tester/enb.yml
