---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: pgw
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-s5u", "interface": "net1"},
      { "name": "lte-s5c", "interface": "net2"},
      { "name": "lte-sgi", "interface": "net3"}
    ]'
spec:
  restartPolicy: OnFailure
  containers:
  - image: electrocucaracha/pgw
    name: pgw
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command:
      - "sh"
    args:
      - "/opt/gw-tester/script/init.sh"
    volumeMounts:
      - name: init-script
        mountPath: /opt/gw-tester/script
  volumes:
    - name: init-script
      configMap:
        name: pgw-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-init-script
data:
  init.sh: |
    s5u_ip=$(ifconfig net1 | awk '/inet addr/{print substr($2,6)}')
    s5c_ip=$(ifconfig net2 | awk '/inet addr/{print substr($2,6)}')

    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/gw-tester/pgw.yml
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/gw-tester/pgw.yml
    sed -i "s|sgi_if_name:.*|sgi_if_name: \"net3\"|g" /etc/gw-tester/pgw.yml

    /opt/gw-tester/bin/pgw -config /etc/gw-tester/pgw.yml
