---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: enb
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-euu", "interfaceRequest": "eth1", "ips": [ "10.0.3.254" ] },
      { "name": "lte-s1c", "interfaceRequest": "eth2", "ips": [ "172.21.1.11" ] },
      { "name": "lte-s1u", "interfaceRequest": "eth3", "ips": [ "172.21.0.11" ] }
    ]'
spec:
  containers:
  - image: electrocucaracha/enb
    name: enb
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command: ["/usr/local/bin/enb", "-config", "/etc/gw/config.yml"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/gw
  volumes:
    - name: config-volume
      configMap:
        name: gw-config
        items:
          - key: enb
            path: config.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: mme
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-s11", "interfaceRequest": "eth1", "ips": [ "172.22.0.12" ] },
      { "name": "lte-s1c", "interfaceRequest": "eth2", "ips": [ "172.21.1.12" ] }
    ]'
spec:
  containers:
  - image: electrocucaracha/mme
    name: mme
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command: ["/usr/local/bin/mme", "-config", "/etc/gw/config.yml"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/gw
  volumes:
    - name: config-volume
      configMap:
        name: gw-config
        items:
          - key: mme
            path: config.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: sgw
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-s11", "interfaceRequest": "eth1", "ips": [ "172.22.0.13" ] },
      { "name": "lte-s1u", "interfaceRequest": "eth2", "ips": [ "172.21.0.13" ] },
      { "name": "lte-s5u", "interfaceRequest": "eth3", "ips": [ "172.25.0.13" ] },
      { "name": "lte-s5c", "interfaceRequest": "eth4", "ips": [ "172.25.1.13" ] }
    ]'
spec:
  containers:
  - image: electrocucaracha/sgw
    name: sgw
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command: ["/usr/local/bin/sgw", "-config", "/etc/gw/config.yml"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/gw
  volumes:
    - name: config-volume
      configMap:
        name: gw-config
        items:
          - key: sgw
            path: config.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: pgw
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-s5u", "interfaceRequest": "eth1", "ips": [ "172.25.0.14" ] },
      { "name": "lte-s5c", "interfaceRequest": "eth2", "ips": [ "172.25.1.14" ] },
      { "name": "lte-sgi", "interfaceRequest": "eth3", "ips": [ "10.0.1.254" ] }
    ]'
spec:
  containers:
  - image: electrocucaracha/mme
    name: pgw
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command: ["/usr/local/bin/mme", "-config", "/etc/gw/config.yml"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/gw
  volumes:
    - name: config-volume
      configMap:
        name: gw-config
        items:
          - key: pgw
            path: config.yml
---
