---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: external-client
  annotations:
    ns.networkservicemesh.io: lte-network/euu1?link=euu
  labels:
    app.kubernetes.io/name: external-client
spec:
  serviceAccount: nse-acc
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: network
                operator: In
                values:
                  - e-utran
          topologyKey: "kubernetes.io/hostname"
  containers:
    - image: electrocucaracha/curl:7.67.0-alpine3.11
      name: external-client
      command:
        - "sh"
      args:
        - "/opt/external-client/script/init.sh"
      env:
        - name: HTTP_SERVER_SGI_IP
          value: {{env.Getenv "HTTP_SERVER_SGI_IP"}}
      volumeMounts:
        - name: init-script
          mountPath: /opt/external-client/script
  volumes:
    - name: init-script
      configMap:
        name: external-client-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-client-init-script
  labels:
    app.kubernetes.io/name: external-client
data:
  init.sh: |
    while true; do
        curl -s --connect-timeout 5 ${HTTP_SERVER_SGI_IP} | sed -e 's/<[^>]*>//g'
        sleep 30
    done
