---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: http-server
  annotations:
    ns.networkservicemesh.io: lte-network/sgi0?link=sgi
  labels:
    network: pdn
spec:
  serviceAccount: nse-acc
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: network
                operator: In
                values:
                  - pdn
          topologyKey: "kubernetes.io/hostname"
  containers:
    - image: python:3.8.2-alpine3.11
      name: http-server
      command: ["python", "-m", "http.server", "80"]
