---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: http-server
  annotations:
    v1.multus-cni.io/default-network: lte-sgi
    danm.k8s.io/interfaces: |
      [
        {"clusterNetwork":"lte-sgi"}
      ]
  labels:
    app.kubernetes.io/name: http-server
    network: pdn
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: network
                operator: In
                values:
                  - pdn
          topologyKey: "kubernetes.io/hostname"
  initContainers:
    - name: configure
      image: httpd:2.4.46-alpine
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      command: ["ip", "route", "add", "10.0.3.0/24", "via", "$(pgw_sgi_ip)"]
      env:
        - name: pgw_sgi_ip
          value: {{env.Getenv "PGW_SGI_IP"}}
  containers:
    - image: httpd:2.4.46-alpine
      name: http-server
