---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: pgw
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {"name": "lte-s5u", "interface": "s5u1"},
        {"name": "lte-s5c", "interface": "s5c2"},
        {"name": "lte-sgi", "interface": "sgi3"}
      ]
    danm.k8s.io/interfaces: |
      [
        {"clusterNetwork":"default"},
        {"clusterNetwork":"lte-s5u"},
        {"clusterNetwork":"lte-s5c"},
        {"clusterNetwork":"lte-sgi"}
      ]
  labels:
    app.kubernetes.io/name: pgw
    network: pdn
spec:
  containers:
    - image: electrocucaracha/pgw:0.7.5
      name: pgw
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      command:
        - "sh"
      args:
        - "/opt/gw-tester/script/init.sh"
      volumeMounts:
        - name: init-script
          mountPath: /opt/gw-tester/script
  volumes:
    - name: init-script
      configMap:
        name: pgw-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-init-script
data:
  init.sh: |
    s5u_ip=$(ifconfig s5u1 | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/gw-tester/pgw.yml

    s5c_ip=$(ifconfig s5c2 | awk '/inet addr/{print substr($2,6)}')
    curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip -XPUT -d value="$s5c_ip" > /dev/null
    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/gw-tester/pgw.yml

    sgi_if_name="sgi3"
    sed -i "s|sgi_if_name:.*|sgi_if_name: \"${sgi_if_name}\"|g" /etc/gw-tester/pgw.yml

    ip a
    ip route
    cat /etc/gw-tester/pgw.yml

    /opt/gw-tester/bin/pgw -config /etc/gw-tester/pgw.yml
