---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: pgw
  labels:
    app.kubernetes.io/name: pgw
    network: pdn
spec:
  serviceAccount: nse-acc
  initContainers:
    - name: install
      image: electrocucaracha/pgw:0.7.5
      command: ["cp", "/etc/gw-tester/pgw.yml", "/work-dir/pgw.yml"]
      volumeMounts:
        - name: config
          mountPath: /etc/gw-tester/
        - name: workdir
          mountPath: /work-dir
  containers:
    - name: sidecar-sgi
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=http-server-sgi"
        - name: IP_ADDRESS
          value: "10.0.1.0/24"
        - name: ROUTE
          value: "10.0.3.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: sidecar-s5u
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=pgw-s5u"
        - name: IP_ADDRESS
          value: "172.25.0.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: sidecar-s5c
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=pgw-s5c"
        - name: IP_ADDRESS
          value: "172.25.1.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - image: electrocucaracha/pgw:0.7.5
      name: pgw
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      command:
        - "sh"
      args:
        - "/opt/gw-tester/script/init.sh"
      volumeMounts:
        - name: init-script
          mountPath: /opt/gw-tester/script
        - name: workdir
          mountPath: /etc/gw-tester
  volumes:
    - name: init-script
      configMap:
        name: pgw-init-script
    - name: workdir
      emptyDir: {}
    - name: config
      configMap:
        name: pgw-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-init-script
data:
  init.sh: |
    until ip route get 172.25.0.0 | grep -q nsm; do
        sleep 2
    done
    s5u_ip=$(ip route get 172.25.0.0 | awk '{ print $6}')
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/gw-tester/pgw.yml

    until ip route get 172.25.1.0 | grep -q nsm; do
        sleep 2
    done
    s5c_ip=$(ip route get 172.25.1.0 | awk '{ print $6}')
    curl -s "${LTE_ETCD_PORT/tcp/http}/v2/keys/pgw_s5c_ip" -XPUT -d value="$s5c_ip" > /dev/null
    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/gw-tester/pgw.yml

    until ip route get 10.0.1.0 | grep -q nsm; do
        sleep 2
    done
    sgi_if_name=$(ip route get 10.0.1.0 | awk '{ print $4}')
    sed -i "s|sgi_if_name:.*|sgi_if_name: \"${sgi_if_name}\"|g" /etc/gw-tester/pgw.yml

    /opt/gw-tester/bin/pgw -config /etc/gw-tester/pgw.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgw-config
data:
  pgw.yml: |
    local_addresses:
      s5c_ip: "172.25.1.14"
      s5u_ip: "172.25.0.14"
    sgi_if_name: "sgi3"
    route_subnet: "10.0.1.0/24"
