---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: sgw
  labels:
    app.kubernetes.io/name: sgw
    network: epc
spec:
  serviceAccount: nse-acc
  initContainers:
    - name: install
      image: electrocucaracha/sgw:0.7.5
      command: ["cp", "/etc/gw-tester/sgw.yml", "/work-dir/sgw.yml"]
      volumeMounts:
        - name: config
          mountPath: /etc/gw-tester/
        - name: workdir
          mountPath: /work-dir
    - name: nsm-init-container
      image: networkservicemesh/nsm-init:v0.2.0
      env:
        - name: NS_NETWORKSERVICEMESH_IO
          value: lte-network/s5u3?link=s5u,lte-network/s5c4?link=s5c
      resources:
        limits:
          networkservicemesh.io/socket: 1
  containers:
    - name: sidecar-s1u
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=sgw-s1u"
        - name: IP_ADDRESS
          value: "172.21.0.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - name: sidecar-s11
      image: nse:v0.2.0
      env:
        - name: ADVERTISE_NSE_NAME
          value: "lte-network"
        - name: ADVERTISE_NSE_LABELS
          value: "app=sgw-s11"
        - name: IP_ADDRESS
          value: "172.22.0.0/24"
      resources:
        limits:
          networkservicemesh.io/socket: 1
    - image: electrocucaracha/sgw:0.7.5
      name: sgw
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      command:
        - "sh"
      args:
        - "/opt/gw-tester/script/init.sh"
      volumeMounts:
        - name: init-script
          mountPath: /opt/gw-tester/script
        - name: workdir
          mountPath: /etc/gw-tester
  volumes:
    - name: init-script
      configMap:
        name: sgw-init-script
    - name: workdir
      emptyDir: {}
    - name: config
      configMap:
        name: sgw-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgw-init-script
data:
  init.sh: |
    until ip add show s5u3 > /dev/null ; do
        sleep 2
    done
    s5u_ip=$(ifconfig s5u3 | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/gw-tester/sgw.yml

    until ip add show s5c4 > /dev/null ; do
        sleep 2
    done
    s5c_ip=$(ifconfig s5c4 | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/gw-tester/sgw.yml

    until ip route get 172.22.0.0 | grep -q nsm; do
        sleep 2
    done
    s11_ip=$(ip route get 172.22.0.0 | awk '{ print $6}')
    curl -s "${LTE_ETCD_PORT/tcp/http}/v2/keys/sgw_s11_ip" -XPUT -d value="$s11_ip" > /dev/null
    sed -i "s|s11_ip:.*|s11_ip: \"${s11_ip}\"|g" /etc/gw-tester/sgw.yml

    until ip route get 172.21.0.0 | grep -q nsm; do
        sleep 2
    done
    s1u_ip=$(ip route get 172.21.0.0 | awk '{ print $6}')
    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/sgw.yml

    ip a
    ip route
    cat /etc/gw-tester/sgw.yml

    /opt/gw-tester/bin/sgw -config /etc/gw-tester/sgw.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgw-config
data:
  sgw.yml: |
    local_addresses:
      s11_ip: "172.22.0.13"
      s1u_ip: "172.21.0.13"
      s5c_ip: "172.25.1.13"
      s5u_ip: "172.25.0.13"
