---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '2.4'

services:
  http_server:
    image: httpd:2.4.46-alpine
    networks:
      lte-sgi:
        ipv4_address: 10.0.1.201
    depends_on:
      - pgw
    command: [sh, -c, "ip route add 10.0.3.0/24 via 10.0.1.254 && /usr/local/bin/httpd-foreground"]
    cap_add:
      - NET_ADMIN
  external_client:
    image: electrocucaracha/curl:7.67.0-alpine3.11
    networks:
      lte-euu:
        ipv4_address: 10.0.3.201
    depends_on:
      - http_server
    command: [sh, -c, "ip route add 10.0.1.0/24 via 10.0.3.254 && while true; do curl -s --connect-timeout 5 10.0.1.201 | sed -e 's/<[^>]*>//g' && sleep 30; done"]
    cap_add:
      - NET_ADMIN
