---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  networkId: 172.22.0.0
  networkLength: 24
s1u:
  name: lte-s1u
  networkId: 172.21.0.0
  networkLength: 24
s5u:
  name: lte-s5u
  networkId: 172.25.0.0
  networkLength: 24
  interface: s5u3
s5c:
  name: lte-s5c
  networkId: 172.25.1.0
  networkLength: 24
  interface: s5c4
sgi:
  name: lte-sgi
  networkId: 10.0.1.0
  networkLength: 24
euu:
  networkId: 10.0.3.0
  networkLength: 24
