---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  container_prefix: s11
s1u:
  name: lte-s1u
  container_prefix: s1u
s5u:
  name: lte-s5u
  container_prefix: s5u
s5c:
  name: lte-s5c
  container_prefix: s5c

replicaCount: 1

image:
  repository: electrocucaracha/sgw
  pullPolicy: IfNotPresent
  tag: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
