---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

s11:
  name: lte-s11
  networkId: 172.22.0.0
s1c:
  name: lte-s1c
  networkId: 172.21.1.0

sgw:
  s11:
    ip: 172.22.0.13
pgw:
  s5c:
    ip: 172.25.1.14

replicaCount: 1

image:
  repository: electrocucaracha/mme
  pullPolicy: IfNotPresent
  tag: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
